- name: Find Testing Instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/all/pass.yml
  tasks:
    - name: Find instances with a specific tag
      amazon.aws.ec2_instance_info:
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "tag:Environment": "Testing"
      register: instances_found
    
    - name: Add new instance to Ansible inventory
      add_host:
        name: "testing_instance"
        ansible_host: "{{ instance_public_ip }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "~/.ssh/Meital-KeyPair.pem"
    
- name: Test the Flask App
  hosts: testing_instance
  tasks:
      - name: Check if app is running
        ansible.builtin.shell: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:5000
        register: http_response
        failed_when: http_response.stdout != "200"
